dist: trusty
sudo: false

language: node_js

node_js:
  - "14"
  - "12"
  - "10"

script:
  - if [[ "$TRAVIS_NODE_VERSION" == 10 ]]; then
      npm run lint;
    fi
  - npm run test:coverage
  - npm run build

deploy:
- provider: s3
  access_key_id: ${ACCESS_KEY_ID}
  secret_access_key: ${SECRET_ACCESS_KEY}
  bucket: cdn.deepstream.io
  skip_cleanup: true
  acl: public_read
  local_dir: dist/bundle
  upload-dir: js/client/latest
  region: eu-central-1
  on:
    tags: true
    node_js: '10'
- provider: npm
  email: "info@deepstream.io"
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
  on:
    tags: true
    node_js: '10'

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  email: false
